/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.net.tenteclicar;

/**
 *
 * @author Lan House
 */
public class TelaTenteClicar extends javax.swing.JFrame {
    /**
     * Creates new form TelaTenteClicar
     */
    public TelaTenteClicar() {
        initComponents();
        btnDois.setVisible(false);
        btnTres.setVisible(false);
        btnQuato.setVisible(false);
        btnCinco.setVisible(false);
        btnSeis.setVisible(false);
        btnSete.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnUm = new javax.swing.JButton();
        btnDois = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnQuato = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnSete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tente clicar no botão 1 vezes");

        btnUm.setText("Venha");
        btnUm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnUmMouseMoved(evt);
            }
        });

        btnDois.setText("Venha");
        btnDois.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDoisMouseMoved(evt);
            }
        });

        btnTres.setText("Venha");
        btnTres.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnTresMouseMoved(evt);
            }
        });

        btnQuato.setText("Venha");
        btnQuato.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnQuatoMouseMoved(evt);
            }
        });

        btnCinco.setText("Venha");
        btnCinco.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCincoMouseMoved(evt);
            }
        });

        btnSeis.setText("Venha");
        btnSeis.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSeisMouseMoved(evt);
            }
        });

        btnSete.setText("Venha");
        btnSete.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSeteMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDois)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnUm))
                    .addComponent(btnSeis))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnQuato)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTres)
                                .addGap(176, 176, 176))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(251, 251, 251)))
                        .addComponent(btnSete))))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btnCinco)
                .addGap(0, 551, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSete)
                    .addComponent(jLabel1))
                .addGap(72, 72, 72)
                .addComponent(btnUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(btnTres)
                .addGap(81, 81, 81)
                .addComponent(btnQuato)
                .addGap(20, 20, 20)
                .addComponent(btnCinco)
                .addGap(55, 55, 55)
                .addComponent(btnDois)
                .addGap(9, 9, 9)
                .addComponent(btnSeis))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUmMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUmMouseMoved
        // TODO add your handling code here:
        btnUm.setVisible(false);
        btnDois.setVisible(true);
    }//GEN-LAST:event_btnUmMouseMoved

    private void btnDoisMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoisMouseMoved
        // TODO add your handling code here:
        btnDois.setVisible(false);
        btnTres.setVisible(true);
    }//GEN-LAST:event_btnDoisMouseMoved

    private void btnTresMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTresMouseMoved
        // TODO add your handling code here:
        btnTres.setVisible(false);
        btnQuato.setVisible(true);
    }//GEN-LAST:event_btnTresMouseMoved

    private void btnQuatoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuatoMouseMoved
        // TODO add your handling code here:
        btnQuato.setVisible(false);
        btnCinco.setVisible(true);
    }//GEN-LAST:event_btnQuatoMouseMoved

    private void btnCincoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCincoMouseMoved
        // TODO add your handling code here:
        btnCinco.setVisible(false);
        btnSeis.setVisible(true);
    }//GEN-LAST:event_btnCincoMouseMoved

    private void btnSeisMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeisMouseMoved
        // TODO add your handling code here:
        btnSeis.setVisible(false);
        btnSete.setVisible(true);
    }//GEN-LAST:event_btnSeisMouseMoved

    private void btnSeteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeteMouseMoved
        // TODO add your handling code here:
        btnSete.setVisible(false);
        btnDois.setVisible(true);
    }//GEN-LAST:event_btnSeteMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTenteClicar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTenteClicar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTenteClicar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTenteClicar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTenteClicar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnDois;
    private javax.swing.JButton btnQuato;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSete;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUm;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
